"""ParHora disease reference table extracted from ParHora-disease.xlsx.

Nakshatra fields are filled from exact disease-name matches against knowledge_base.NAKSHATRA_DISEASES.
"""

PARHORA_TABLE = [{'planet': 'SUN', 'disease': 'disease of nerves & brains', 'organs': 'Nervous system, brain', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'cellular excitation', 'organs': 'Brain', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'weak constituion', 'organs': 'Digestive', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'dryness', 'organs': 'Skin, Liver', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'apoplexy', 'organs': 'Brain, Adrenal Gland', 'nakshatra': 'Poorvabhadra'},
 {'planet': 'SUN', 'disease': 'disease of arteries', 'organs': 'Heart, Brain', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'bowel disorders', 'organs': 'Excretion', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'pimples', 'organs': 'Skin, Liver', 'nakshatra': 'Krithika, Mrigashira'},
 {'planet': 'SUN','disease': 'skin & throat affliction','organs': 'Allergic Infection, Throat, Lungs, Skin','nakshatra': ''},
 {'planet': 'SUN', 'disease': 'chronic inflamation', 'organs': 'Skin, Immunity, Infection', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'conjuctivitis', 'organs': 'Eye', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'Diptheria', 'organs': 'Infection, Nerves, Brain, heart', 'nakshatra': 'Mrigashira, Aridra'},
 {'planet': 'SUN', 'disease': 'dizziness', 'organs': 'Heart, Brain', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'dropsy (jupiter)', 'organs': 'Swelling in organs', 'nakshatra': 'Poorvabhadra, Punarvasu, Uttara Bhadrapada'},
 {'planet': 'SUN', 'disease': 'fever', 'organs': 'Infection, Nerves, Brain, heart', 'nakshatra': 'Krithika, Chitha'},
 {'planet': 'SUN', 'disease': 'fistula', 'organs': 'Excretory,Anus, Colon', 'nakshatra': 'Jyesta'},
 {'planet': 'SUN', 'disease': 'giddiness', 'organs': 'Hearth, Kidney, Brain', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'glucoma', 'organs': 'Eye', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'violent pains & headache', 'organs': 'Heart, Brain', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'organic heart troubles', 'organs': 'Heart', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'palpitation disorder', 'organs': 'Heart', 'nakshatra': 'Uttara Phalguni, Dhanishta, Uttaraashada'},
 {'planet': 'SUN', 'disease': 'hyper anaemia', 'organs': 'Heart', 'nakshatra': 'Uttara Phalguni, Ashwini'},
 {'planet': 'SUN','disease': 'affliction to excretory & generative systems',
  'organs': 'Sex Organs, usually discharging type',
  'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'measels', 'organs': 'Infection, Skin', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'obstruction in the stomach', 'organs': 'Stomach', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'quinsy', 'organs': 'Throat, Tonsil', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'scrofula', 'organs': 'TB of neck', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'scurvy', 'organs': 'Teeth, Skin', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'sharpness of urine', 'organs': 'Urinary tract, penis', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'smallpox', 'organs': 'Infection,', 'nakshatra': 'Ashwini'},
 {'planet': 'SUN', 'disease': 'disorders of spine', 'organs': 'Backbone, Spinal Chord', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'strangury', 'organs': 'urinary tract, penis', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'sunstrokes', 'organs': 'Multiple organs', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'swellings in neck or feet (high BP)', 'organs': 'Heart', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'trembling', 'organs': 'Brain', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'tumours', 'organs': 'All organs', 'nakshatra': ''},
 {'planet': 'SUN', 'disease': 'veneral ditempers', 'organs': 'Sexual Organs', 'nakshatra': 'Mrigashira, Bharani'},
 {'planet': 'MARS', 'disease': 'death by abortions', 'organs': 'Uterus, Foetus, Blood', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'disorder of blood vessels', 'organs': 'Bllood, Heart, Brain', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'bleeding', 'organs': 'Blood,', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'excessive menses', 'organs': 'Uterus', 'nakshatra': 'Rohini, Vishaka'},
 {'planet': 'MARS', 'disease': 'boils', 'organs': 'Mouth', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'afflictions & pains in breast', 'organs': 'Breast, Chest', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'burns', 'organs': 'Skin', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'bruises', 'organs': 'Injusries', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'carbuncles', 'organs': 'Skin, Infections', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'chickenpox', 'organs': 'Skin, Infections', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'congestion of blood', 'organs': 'Heart', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'blood consumption', 'organs': 'Heart', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'contagious fever', 'organs': 'Infections', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'cutaneous eruptions', 'organs': 'Skin', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'fatty degeneration of heart', 'organs': 'Heart', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'dysentry', 'organs': 'Gastrointestinal', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'epidemic', 'organs': 'Infection, Lungs', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'fracture & falls', 'organs': 'Injury, Bones', 'nakshatra': 'Shathabhisha, Uttara Bhadrapada, Dhanishta'},
 {'planet': 'MARS', 'disease': 'disorders of genital-unrinal organs', 'organs': 'Sex Organs', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'gonorrohea', 'organs': 'Unnatural Sex, Sex organs', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'haemoptysis', 'organs': 'Lungs, Bronchial', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'hernia', 'organs': 'Abdomenal', 'nakshatra': 'Uttara Bhadrapada'},
 {'planet': 'MARS', 'disease': 'hysteria', 'organs': 'Mind', 'nakshatra': 'Hasta'},
 {'planet': 'MARS', 'disease': 'itches', 'organs': 'Skin, Infections', 'nakshatra': 'Mrigashira'},
 {'planet': 'MARS', 'disease': 'loss of blood', 'organs': 'Accident, Injury', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'hemorrhage of lungs', 'organs': 'Lungs, Heart', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'malaria (with Rahu)', 'organs': 'Abdomenal', 'nakshatra': 'Krithika'},
 {'planet': 'MARS', 'disease': 'ulceration of penis', 'organs': 'Penis, Sex organ', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'perityphilitis', 'organs': 'Gastro-intestinal', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'piles', 'organs': 'Excretory, Anus', 'nakshatra': 'Anuradha'},
 {'planet': 'MARS', 'disease': 'semiterial fevers', 'organs': 'Insect bite Infection, Chest, Abdomen', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'syphilis', 'organs': 'Sexual Organs', 'nakshatra': 'Bharani'},
 {'planet': 'MARS', 'disease': 'extreme heat in throat', 'organs': 'Infection, Throat, Liver', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'tonsils', 'organs': 'Throat', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'vascular excitement', 'organs': 'Mind, Sexual organs', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'abscess of valva', 'organs': 'Vagina, Sexual organ', 'nakshatra': ''},
 {'planet': 'MARS', 'disease': 'yellow jaundice', 'organs': 'Liver', 'nakshatra': 'Poorvabhadra'},
 {'planet': 'JUPITER',
  'disease': 'Adiposis',
  'organs': 'fatty growth in buttock, upper arms, upper legs,',
  'nakshatra': ''},
 {'planet': 'JUPITER',
  'disease': 'disorders of adrenal',
  'organs': 'digestion, immune system, heart/BP',
  'nakshatra': 'Vishaka'},
 {'planet': 'JUPITER', 'disease': 'disease from corrupt air', 'organs': 'Lungs, Brochia, nasal', 'nakshatra': ''},
 {'planet': 'JUPITER', 'disease': 'change in RBCs', 'organs': 'Blood supply to leg & arms', 'nakshatra': ''},
 {'planet': 'JUPITER','disease': 'disorder of arterial blood','organs': 'blood supply to leg & arms','nakshatra': ''},
 {'planet': 'JUPITER', 'disease': 'disorder in the back end of backbone', 'organs': 'backbone', 'nakshatra': ''},
 {'planet': 'JUPITER', 'disease': 'stone in bladder', 'organs': 'Urinary Bladder', 'nakshatra': 'Chitha, Magha'},
 {'planet': 'JUPITER', 'disease': 'cancer of the breast', 'organs': 'breast', 'nakshatra': ''},
 {'planet': 'JUPITER', 'disease': 'cerebral congestion', 'organs': 'brain', 'nakshatra': 'Ashwini, Vishaka'},
 {'planet': 'JUPITER', 'disease': 'digestive disorders', 'organs': 'stomach', 'nakshatra': 'Uttaraashada'},
 {'planet': 'JUPITER','disease': 'dropsy','organs': 'Edema/swelling in various organs','nakshatra': 'Poorvabhadra, Punarvasu, Uttara Bhadrapada'},
 {'planet': 'JUPITER', 'disease': 'afflictions of ear', 'organs': 'Ear', 'nakshatra': ''},
 {'planet': 'JUPITER', 'disease': 'eczema', 'organs': 'skin', 'nakshatra': 'Pushya, Shravana, Swathi'},
 {'planet': 'JUPITER', 'disease': 'kidney tumour', 'organs': 'kidney', 'nakshatra': 'Magha, Vishaka'},
 {'planet': 'JUPITER', 'disease': 'disturbance of milk glands', 'organs': 'breast', 'nakshatra': ''},
 {'planet': 'JUPITER', 'disease': 'fatty degeneration of muscles', 'organs': 'all muscles', 'nakshatra': ''},
 {'planet': 'JUPITER','disease': 'plethoric & sthenic disturbances','organs': 'nervous or vasular disorder','nakshatra': ''},
 {'planet': 'JUPITER', 'disease': 'potato like cancer', 'organs': 'pancreas/stomach', 'nakshatra': ''},
 {'planet': 'JUPITER','disease': 'thoracic diathesis','organs': 'food pipe, esophagus, lungs injury/bleed','nakshatra': ''},
 {'planet': 'JUPITER', 'disease': 'pains in vertebrae', 'organs': 'Vertebrae, Back bone', 'nakshatra': ''},
 {'planet': 'JUPITER',
  'disease': 'diseases of viscera',
  'organs': 'digestive, stomach, excertory, etc',
  'nakshatra': ''},
 {'planet': 'JUPITER', 'disease': 'diseasesof liver', 'organs': 'Liver', 'nakshatra': 'Poorvabhadra, Punarvasu'},
 {'planet': 'JUPITER', 'disease': 'disease of spleen', 'organs': 'Spleen (stomach)', 'nakshatra': ''},
 {'planet': 'SATURN', 'disease': 'Antiperistalsis', 'organs': 'bones, knee joints', 'nakshatra': ''},
 {'planet': 'SATURN', 'disease': 'arthritis', 'organs': 'Joints', 'nakshatra': ''},
 {'planet': 'SATURN', 'disease': 'articular rheumatism', 'organs': 'Joints', 'nakshatra': 'Shathabhisha, Moola'},
 {'planet': 'SATURN', 'disease': 'black jaundice', 'organs': 'Penis, Vaginal, Blood, Unprotected sex', 'nakshatra': 'Poorvabhadra'},
 {'planet': 'SATURN', 'disease': 'fracture & pain in bones', 'organs': 'bones, legs', 'nakshatra': 'Anuradha'},
 {'planet': 'SATURN', 'disease': 'chronic bronchitis', 'organs': 'bronchia, lungs', 'nakshatra': ''},
 {'planet': 'SATURN', 'disease': 'impotence', 'organs': 'sexual organs', 'nakshatra': ''},
 {'planet': 'SATURN', 'disease': 'club feet', 'organs': 'congenital feet disorder', 'nakshatra': ''},
 {'planet': 'SATURN', 'disease': 'cold', 'organs': 'nasal, bronchial', 'nakshatra': 'Bharani, Rohini'},
 {'planet': 'SATURN', 'disease': 'deafness', 'organs': 'ear', 'nakshatra': ''},
 {'planet': 'SATURN', 'disease': 'dyspnea (shortness of breath)', 'organs': 'Lungs, chest', 'nakshatra': ''},
 {'planet': 'SATURN',
  'disease': 'typhoid',
  'organs': 'Blood, gastro-intestine, gall bladder, etc',
  'nakshatra': 'Hasta'},
 {'planet': 'SATURN', 'disease': 'disorder of faetus & conception', 'organs': 'uterus', 'nakshatra': ''},
 {'planet': 'SATURN',
  'disease': 'narrowing of passage (muscles) Heart',
  'organs': 'Heart other organs also',
  'nakshatra': ''},
 {'planet': 'SATURN', 'disease': 'poisoning', 'organs': 'Heart', 'nakshatra': 'Dhanishta'},
 {'planet': 'SATURN', 'disease': 'depression in skull', 'organs': 'Head', 'nakshatra': ''},
 {'planet': 'SATURN', 'disease': 'lumpy & hard stool', 'organs': 'Intestinal tract', 'nakshatra': ''},
 {'planet': 'SATURN', 'disease': 'ablation of tonsils', 'organs': 'Tonsil, neck', 'nakshatra': ''},
 {'planet': 'SATURN', 'disease': 'dental diseases', 'organs': 'Teeth', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'gaseous distension of abdomen', 'organs': 'Abdomen', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'abscesses', 'organs': 'any organ', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'disease of alimentary canal', 'organs': 'Oesophagus', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'disorders of bladders', 'organs': 'Bladder, Urinary system', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'blindness', 'organs': 'Eye, Brain', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'disorders of bowel', 'organs': 'Abdominal, Intestine', 'nakshatra': ''},
 {'planet': 'MOON',
  'disease': 'disorders of the brain substance',
  'organs': 'Brain, protection fluid of brain',
  'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'bronchial disorders', 'organs': 'Respiratory, Bronchia', 'nakshatra': ''},
 {'planet': 'MOON',
  'disease': 'cancer',
  'organs': 'Multiple organs, abnormal cells/tissues of Skin, Bones/Muscle, Blood, Immune/Lymph',
  'nakshatra': 'Pushya'},
 {'planet': 'MOON', 'disease': 'carditis', 'organs': 'Heart', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'cataract', 'organs': 'Eyes', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'cellular zymosis', 'organs': 'Sever fatal infections', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'worms in children age', 'organs': 'intestinal', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'cold', 'organs': 'throat', 'nakshatra': 'Bharani, Rohini'},
 {'planet': 'MOON', 'disease': 'conjuctivitis', 'organs': 'Eyes', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'rotten coughs', 'organs': 'throat, lungs', 'nakshatra': 'Aridra'},
 {'planet': 'MOON', 'disease': 'delirium (Rahu driven)', 'organs': 'Mind, Brain', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'diarrohea', 'organs': 'Stomach Infection', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'irregular menses', 'organs': 'Blood, Harmonal', 'nakshatra': 'Rohini'},
 {'planet': 'MOON', 'disease': 'mestural disorders', 'organs': 'Harmonal, Sexual organs', 'nakshatra': 'Rohini'},
 {'planet': 'MOON', 'disease': 'dyspepsia', 'organs': 'Indigestion, Stomach', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'effusion', 'organs': 'Lungs', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'epilepsy', 'organs': 'Neurological, Brain', 'nakshatra': 'Ashwini'},
 {'planet': 'MOON', 'disease': 'eruptions', 'organs': 'Skin', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'disorder of eyes', 'organs': 'Eyes', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'gout in feet', 'organs': 'Joints, Bones', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'osmotic sydrome', 'organs': 'Neurological, Mind, Brain', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'leucorrhea', 'organs': 'Vagina, Sex Organ', 'nakshatra': 'Jyesta'},
 {'planet': 'MOON', 'disease': 'disease of genitals', 'organs': 'Sex organs', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'haemoglobin issues', 'organs': 'Blood', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'hysteria', 'organs': 'Mind, Brain', 'nakshatra': 'Hasta'},
 {'planet': 'MOON', 'disease': 'mental illhealth', 'organs': 'Mind, Brain', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'stone in kidneys (venus)', 'organs': 'Kidneys', 'nakshatra': 'Magha'},
 {'planet': 'MOON', 'disease': 'scrofula', 'organs': 'TB of neck', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'disorders of larynx', 'organs': 'neck, voice box', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'disorder of breasts', 'organs': 'Breasts, Chest', 'nakshatra': 'Rohini'},
 {'planet': 'MOON',
  'disease': 'diseases of mucous/serous membranes',
  'organs': 'Lungs, Heart, Ctomach',
  'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'miscarriage', 'organs': 'Blood, Uterus, Foetus', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'obstruction of bowels & lungs', 'organs': 'Gastro-intestinal', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'phthisis', 'organs': 'TB, lungs, liver, spleen, gastro', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'premature birth', 'organs': 'Brains, Lungs, Uterus, Blood', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'profluvial effusions', 'organs': 'Lungs', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'thin blood', 'organs': 'Heart', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'disorder of uterus', 'organs': 'Uterus', 'nakshatra': ''},
 {'planet': 'MOON', 'disease': 'nausea/vomiting', 'organs': 'Heart, Brain, Digestion', 'nakshatra': ''},
 {'planet': 'MERCURY', 'disease': 'nervousness complaints', 'organs': 'Mind, Heart', 'nakshatra': ''},
 {'planet': 'MERCURY', 'disease': 'asthma', 'organs': 'Lungs, Nasal', 'nakshatra': 'Aridra'},
 {'planet': 'MERCURY', 'disease': 'apoplexy', 'organs': 'Brain, Adrenal Gland', 'nakshatra': 'Poorvabhadra'},
 {'planet': 'MERCURY', 'disease': 'impure blood (Rahu)', 'organs': 'Multiple organs', 'nakshatra': ''},
 {'planet': 'MERCURY',
  'disease': 'disorders caused to brain due to overwork',
  'organs': 'Brian, Mind',
  'nakshatra': ''},
 {'planet': 'MERCURY', 'disease': 'rapid breathing', 'organs': 'Mind,  Lungs', 'nakshatra': 'Hasta'},
 {'planet': 'MERCURY', 'disease': 'shortness of breath', 'organs': 'Heart, Lungs', 'nakshatra': 'Hasta'},
 {'planet': 'MERCURY', 'disease': 'colic in bowels', 'organs': 'Excretory organs', 'nakshatra': ''},
 {'planet': 'MERCURY', 'disease': 'cramps in the arms', 'organs': 'Arms', 'nakshatra': ''},
 {'planet': 'MERCURY', 'disease': 'cramps in shoulders', 'organs': 'Shoulders', 'nakshatra': 'Mrigashira'},
 {'planet': 'MERCURY', 'disease': 'crams in legs & feet', 'organs': 'Legs', 'nakshatra': ''},
 {'planet': 'MERCURY', 'disease': 'dumbness', 'organs': 'Brain, Mind, Ear', 'nakshatra': ''},
 {'planet': 'MERCURY', 'disease': 'falling fits', 'organs': 'Brain', 'nakshatra': ''},
 {'planet': 'MERCURY', 'disease': 'flatulent colic', 'organs': 'Stomach', 'nakshatra': ''},
 {'planet': 'MERCURY', 'disease': 'gastro-abdominal troubles', 'organs': 'Gastro-abdomen', 'nakshatra': ''},
 {'planet': 'MERCURY', 'disease': 'hypersthesia', 'organs': 'Sensory, nerves', 'nakshatra': ''},
 {'planet': 'MERCURY', 'disease': 'insomnia', 'organs': 'Mind, Brain', 'nakshatra': ''},
 {'planet': 'MERCURY',
  'disease': 'neuralgia & obstruction in kidney',
  'organs': 'Nerves, Face, kidney',
  'nakshatra': ''},
 {'planet': 'MERCURY', 'disease': 'paralysis of nervous system', 'organs': 'Nervous systems, Brain', 'nakshatra': 'Uttaraashada'},
 {'planet': 'MERCURY', 'disease': 'pulmonary disease', 'organs': 'Lungs, Respiratory track', 'nakshatra': 'Uttaraashada, Punarvasu, Moola'},
 {'planet': 'MERCURY', 'disease': 'quivering', 'organs': 'Mind, Brain', 'nakshatra': ''},
 {'planet': 'MERCURY', 'disease': 'griping in stomach', 'organs': 'Mind, tension', 'nakshatra': ''},
 {'planet': 'MERCURY', 'disease': 'suppresion of urine', 'organs': 'Mind, Kidney', 'nakshatra': ''},
 {'planet': 'MERCURY', 'disease': 'heart tremors', 'organs': 'Tension, Heart', 'nakshatra': 'Poorvabhadra, Dhanishta'},
 {'planet': 'MERCURY',
  'disease': 'reduction of the vital fluids of nerves',
  'organs': 'Sensory, skin',
  'nakshatra': ''},
 {'planet': 'MERCURY', 'disease': 'worms in bowel', 'organs': 'Intenstines', 'nakshatra': ''},
 {'planet': 'VENUS', 'disease': 'Comedo', 'organs': 'skin', 'nakshatra': ''},
 {'planet': 'VENUS', 'disease': 'bowels disorder wrt mucous/flux etc', 'organs': 'bowel', 'nakshatra': ''},
 {'planet': 'VENUS', 'disease': 'breathing disorders', 'organs': 'lungs, bronchial', 'nakshatra': 'Hasta'},
 {'planet': 'VENUS', 'disease': "Bright's disease", 'organs': '', 'nakshatra': ''},
 {'planet': 'VENUS', 'disease': 'poor criculations of veins blood', 'organs': 'Blood, Veins, Heart', 'nakshatra': ''},
 {'planet': 'VENUS', 'disease': 'clogging of blood system', 'organs': 'Heart', 'nakshatra': ''},
 {'planet': 'VENUS', 'disease': 'skin disorders', 'organs': 'Skin', 'nakshatra': 'Uttaraashada, Shravana'},
 {'planet': 'VENUS', 'disease': 'diabetes', 'organs': 'Blood, Kidney', 'nakshatra': 'Poorvashada'},
 {'planet': 'VENUS', 'disease': 'diptheria', 'organs': 'nose, throat, breathing', 'nakshatra': 'Mrigashira, Aridra'},
 {'planet': 'VENUS', 'disease': 'enlarged tonsils', 'organs': 'Tonsil, throat', 'nakshatra': ''},
 {'planet': 'VENUS', 'disease': 'humorous discharge from eyes', 'organs': 'Eyes', 'nakshatra': 'Krithika'},
 {'planet': 'VENUS', 'disease': 'skin erupions & other issues in feet', 'organs': 'Feet,Skin', 'nakshatra': ''},
 {'planet': 'VENUS', 'disease': 'bilious flatulency', 'organs': 'Stomach, Liver, GAS', 'nakshatra': ''},
 {'planet': 'VENUS', 'disease': 'hysteria', 'organs': 'Mind', 'nakshatra': 'Hasta'},
 {'planet': 'VENUS', 'disease': 'disease of kidneys', 'organs': 'Kidneys', 'nakshatra': ''},
 {'planet': 'VENUS', 'disease': "King's Evil (TB)", 'organs': 'Lungs, bronchial', 'nakshatra': ''},
 {'planet': 'VENUS',
  'disease': 'disease of matrix',
  'organs': 'Tissue/cellular connectivity causing cancers, fibrosis',
  'nakshatra': ''},
 {'planet': 'VENUS', 'disease': 'Night-sleep penis discharge', 'organs': 'sexual organs', 'nakshatra': ''},
 {'planet': 'VENUS', 'disease': 'veneral disorders', 'organs': 'sexual organs', 'nakshatra': ''},
 {'planet': 'VENUS', 'disease': 'thorax disorders', 'organs': 'Lungs', 'nakshatra': ''},
 {'planet': 'VENUS',
  'disease': 'typhus fever',
  'organs': 'infections in lungs, skin, liver, brain, kidney',
  'nakshatra': ''},
 {'planet': 'VENUS', 'disease': 'urine infections', 'organs': 'Urinary/Sex organs', 'nakshatra': 'Swathi'}]

PARHORA_BY_PLANET = {}
for row in PARHORA_TABLE:
    PARHORA_BY_PLANET.setdefault(row["planet"], []).append(row)
