from __future__ import annotations

from knowledge_base import RASHI_ORGANS
from rashi_truth_normalization import PLANET_TERM_TO_RASHI_ORGANS as NORMALIZED_PLANET_TERM_TO_RASHI_ORGANS
 
# ============================================================
# UPDATED NAKSHATRA DISEASE → ALL_ORGANS MAPPING
# - All 173 diseases remapped to ALL_ORGANS superset
# - All 101 organs covered (99 mapped to diseases + 2 planetary meta-tags)
# - Key additions: Skin, Bone Marrow, Anus, Excretory Organs, Testicles,
#   Groins, Liver, Spleens, Muscle, Respiratory Canal, Fever, Lymphatic
#   System, Emotions and Desires, Waist, Memory, Speech, Solar Plexes,
#   Naval/Navels, Loins, Psychic Faculty, Fat in the body, Impotency,
#   Sex urge, Enlargement of spleen, Unknown diseases
# ============================================================
 
ALL_ORGANS = [
    "Abdomen",
    "Accute pain",
    "Ankle",
    "Anus",
    "Arms",
    "Bladder",
    "Blood",
    "Body Growth",
    "Body pain",
    "Bone Marrow",
    "Bones",
    "Bowels",
    "Brain",
    "Breast",
    "Breathing",
    "Breathings",
    "Calves",
    "Chest",
    "Collar",
    "Difficulty in breathing",
    "Distributary Systems of Body Fluids",
    "Ears",
    "Emotions and Desires",
    "Energy",
    "Enlargement of spleen",
    "Excretory Organs",
    "Eye",
    "Eyes",
    "Face",
    "Fat in the body",
    "Feet",
    "Female Organs",
    "Fever",
    "Fingers",
    "Flesh",
    "Further all diseases apply to Mars (Kujavat Ketu)",
    "Further everything that apply to Saturn (Shanivat Rahu)",
    "Gas troubles",
    "Genital",
    "Genitals",
    "Groins",
    "Hands",
    "Head",
    "Heart",
    "Hips",
    "Hips Joints",
    "Impotency",
    "Injury",
    "Intestines",
    "Joints",
    "Kidney",
    "Knees",
    "Leg diseases",
    "Leprosy",
    "Liver",
    "Loins",
    "Long lasting diseases",
    "Lower Abdomen",
    "Lower Stomach",
    "Lung trouble",
    "Lungs",
    "Lymphatic System",
    "Memory",
    "Mental Faculties",
    "Mind",
    "Mouth",
    "Muscle",
    "Naval",
    "Navels",
    "Neck",
    "Nerves problems",
    "Nose",
    "Ovaries",
    "Pestilence",
    "Psychic Faculty",
    "Respiratory Canal",
    "Semen",
    "Sex Organs",
    "Sex urge",
    "Shanks",
    "Shoulders",
    "Skin",
    "Solar Plexes",
    "Speech",
    "Spine",
    "Spleens",
    "Stomach",
    "Stomach pain",
    "Teeth",
    "Testicles",
    "Thighs",
    "Throat",
    "Toes",
    "Tongue",
    "Unknown diseases",
    "Upper Back",
    "Upper Chest",
    "Upper Stomach",
    "Urinary Tracts",
    "Waist",
    "Water in the body",
]
 
NAKSHATRA_DISEASE_TO_SUPERSET_ORGANS = {
    "Abdominal disorders": ["Abdomen", "Lower Abdomen", "Stomach", "Bowels", "Stomach pain", "Intestines", "Lower Stomach", "Upper Stomach", "Naval", "Navels", "Solar Plexes"],
    "Abdominal tumour": ["Abdomen", "Lower Abdomen", "Stomach", "Stomach pain", "Lower Stomach"],
    "Abnormal bleeding during menses": ["Female Organs", "Ovaries", "Breast", "Semen", "Genitals", "Sex Organs", "Blood", "Groins"],
    "Accident including fire accidents": ["Bones", "Blood", "Flesh", "Injury", "Skin", "Muscle"],
    "Acute pains in the body": ["Flesh", "Bones", "Accute pain", "Body pain", "Muscle", "Joints"],
    "Affected eyes": ["Eye", "Eyes", "Face", "Nose", "Ears", "Tongue", "Teeth", "Mouth", "Throat", "Neck"],
    "Affliction of bowels": ["Stomach", "Upper Stomach", "Lower Stomach","Hips", "Bowels", "Intestines", "Abdomen", "Lower Abdomen", "Stomach pain","Blood","Excretory Organs", "Anus"],
    "Amputation": ["Hips Joints", "Thighs", "Knees", "Ankle", "Feet", "Toes", "Calves", "Shanks", "Joints", "Bones", "Upper Back", "Spine", "Shoulders", "Arms", "Collar", "Injury", "Fingers", "Hands"],
    "Apoplexy": ["Head", "Brain", "Mind", "Mental Faculties", "Blood", "Nerves problems", "Memory", "Speech"],
    "Asthma": ["Lungs", "Chest", "Breathing", "Breathings", "Throat", "Nose", "Difficulty in breathing", "Lung trouble", "Respiratory Canal"],
    "Bacillary dysentery": ["Blood", "Bowels", "Intestines", "Lower Abdomen", "Stomach pain"],
    "Beri beri": ["Blood", "Nerves problems", "Energy", "Muscle"],
    "Blood poisoning": ["Blood", "Skin", "Flesh"],
    "Blood pressure": ["Heart", "Chest", "Blood", "Upper Back"],
    "Brain fever": ["Head", "Brain", "Mind", "Mental Faculties", "Blood", "Fever", "Memory", "Speech"],
    "Breathing problems": ["Lungs", "Chest", "Breathing", "Breathings", "Throat", "Nose", "Difficulty in breathing", "Lung trouble", "Respiratory Canal"],
    "Cancer": ["Flesh", "Blood", "Skin", "Bone Marrow", "Long lasting diseases", "Unknown diseases"],
    "Cardiac thrombosis": ["Heart", "Chest", "Blood", "Upper Back"],
    "Cerebral anaemia": ["Head", "Brain", "Mind", "Mental Faculties", "Blood"],
    "Cerebral haemorrhages": ["Head", "Brain", "Mind", "Mental Faculties", "Blood"],
    "Choleric humours": ["Blood", "Liver", "Stomach"],
    "Cold": ["Nose", "Throat", "Lungs", "Chest", "Breathings", "Respiratory Canal"],
    "Cold & Cough": ["Nose", "Throat", "Lungs", "Chest", "Breathing", "Breathings", "Respiratory Canal"],
    "Cold foot": ["Feet", "Toes", "Calves", "Leg diseases"],
    "Collar bone fracture": ["Collar", "Bones", "Shoulders", "Arms", "Injury"],
    "Congestion in the brain": ["Head", "Brain", "Mind", "Mental Faculties", "Blood", "Memory"],
    "Congestion of brain": ["Head", "Brain", "Mind", "Mental Faculties", "Blood", "Memory"],
    "Constipation": ["Stomach", "Upper Stomach", "Lower Stomach", "Bowels", "Intestines", "Abdomen", "Lower Abdomen", "Excretory Organs", "Anus"],
    "Corrupted blood": ["Blood", "Skin", "Liver"],
    "Cough & hiccups": ["Lungs", "Chest", "Breathing", "Breathings", "Throat", "Nose", "Respiratory Canal"],
    "Curvature of spine": ["Spine", "Bones", "Upper Back", "Shoulders", "Waist", "Loins"],
    "Cuts": ["Blood", "Injury", "Skin", "Flesh"],
    "Deficiency of adrenal secretion": ["Blood", "Kidney", "Urinary Tracts", "Liver", "Distributary Systems of Body Fluids", "Water in the body", "Energy"],
    "Diabetes": ["Blood", "Kidney", "Urinary Tracts", "Liver", "Distributary Systems of Body Fluids", "Water in the body", "Excretory Organs", "Fat in the body"],
    "Diabetes, Insulin deficiency": ["Blood", "Kidney", "Urinary Tracts", "Liver", "Distributary Systems of Body Fluids", "Water in the body", "Excretory Organs", "Fat in the body"],
    "Digestive disorders": ["Blood", "Stomach", "Bowels", "Intestines", "Liver", "Stomach pain"],
    "Dilated heart": ["Heart", "Chest", "Blood", "Upper Back", "Upper Chest"],
    "Diphtheria": ["Blood", "Throat", "Respiratory Canal", "Neck", "Pestilence"],
    "Diseases of womb": ["Female Organs", "Ovaries", "Genitals", "Sex Organs", "Lower Abdomen", "Groins", "Sex urge"],
    "Dropsy": ["Distributary Systems of Body Fluids", "Lymphatic System", "Blood", "Water in the body", "Kidney", "Heart"],
    "Dry coughs": ["Lungs", "Chest", "Breathing", "Breathings", "Throat", "Nose", "Respiratory Canal"],
    "Ear infections": ["Ears", "Face", "Pestilence"],
    "Eczema": ["Flesh", "Blood", "Skin"],
    "Enlarged Liver": ["Liver", "Abdomen", "Upper Stomach"],
    "Eosinophilia": ["Lungs", "Chest", "Breathing", "Breathings", "Throat", "Nose", "Blood"],
    "Epilepsy": ["Head", "Brain", "Mind", "Mental Faculties", "Nerves problems", "Memory", "Psychic Faculty"],
    "Excess of urine and kidney problem": ["Kidney", "Urinary Tracts", "Bladder", "Water in the body"],
    "Eye sore": ["Eye", "Eyes", "Face"],
    "Fainting": ["Blood", "Brain", "Mind", "Heart", "Energy"],
    "Fibroid tumour": ["Flesh", "Abdomen", "Female Organs", "Lower Abdomen"],
    "Filaria": ["Blood", "Lymphatic System", "Distributary Systems of Body Fluids", "Leg diseases", "Skin", "Enlargement of spleen"],
    "Fracture": ["Bones", "Joints", "Injury"],
    "Fracture in foot": ["Bones", "Feet", "Toes", "Ankle", "Injury"],
    "Fracture of hip bone": ["Bones", "Hips", "Hips Joints", "Injury"],
    "Fracture of legs": ["Bones", "Knees", "Shanks", "Calves", "Feet", "Injury", "Leg diseases"],
    "Frequent micturition": ["Urinary Tracts", "Bladder", "Kidney", "Water in the body"],
    "Gallstones": ["Blood", "Liver", "Abdomen", "Upper Stomach"],
    "Gas formation": ["Stomach", "Upper Stomach", "Lower Stomach", "Bowels", "Intestines", "Abdomen", "Lower Abdomen", "Gas troubles", "Naval", "Navels"],
    "Gas in stomach": ["Stomach", "Upper Stomach", "Lower Stomach", "Bowels", "Gas troubles", "Stomach pain", "Naval", "Navels", "Solar Plexes"],
    "Gastric ulcer": ["Stomach", "Upper Stomach", "Lower Stomach", "Bowels", "Intestines", "Abdomen", "Lower Abdomen", "Gas troubles", "Stomach pain", "Solar Plexes"],
    "Goitre due to Iodine deficiency": ["Blood", "Neck", "Throat", "Lymphatic System"],
    "Grief of poison": ["Blood", "Stomach", "Emotions and Desires", "Mind"],
    "Heart Valves affected": ["Heart", "Chest", "Blood", "Upper Back"],
    "Heart affected by sudden shock": ["Heart", "Chest", "Blood", "Upper Back", "Emotions and Desires", "Mind"],
    "Heart affected due to disappointment of love affairs": ["Heart", "Chest", "Blood", "Upper Back", "Emotions and Desires", "Mind"],
    "Heart affects due to loss of children": ["Heart", "Chest", "Blood", "Upper Back", "Emotions and Desires", "Mind"],
    "Heart failure": ["Heart", "Chest", "Blood", "Upper Back", "Lungs"],
    "Hernia": ["Stomach", "Lower Stomach", "Bowels", "Intestines", "Abdomen", "Lower Abdomen", "Groins", "Muscle", "Loins", "Naval", "Navels"],
    "Hiccups": ["Lungs", "Chest", "Breathing", "Breathings", "Throat", "Nose"],
    "High Blood pressure": ["Heart", "Chest", "Blood", "Upper Back"],
    "Hip diseases": ["Hips Joints", "Thighs", "Bones", "Hips", "Waist", "Loins","Blood","Anus","Bowels", "Excretory Organs"],
    "Hyperaemia": ["Blood", "Skin"],
    "Hysteria": ["Brain", "Mind", "Mental Faculties", "Spine", "Nerves problems", "Emotions and Desires", "Psychic Faculty"],
    "Indigestion": ["Stomach", "Upper Stomach", "Lower Stomach", "Bowels", "Intestines", "Abdomen", "Lower Abdomen", "Stomach pain", "Liver", "Solar Plexes"],
    "Injury in the face": ["Face", "Eye", "Eyes", "Nose", "Ears", "Tongue", "Teeth", "Mouth", "Injury", "Skin"],
    "Injury in the head": ["Head", "Brain", "Mind", "Mental Faculties", "Injury", "Bones"],
    "Injury in the head mostly in the forehead, just around the eyes": ["Head", "Brain", "Mind", "Mental Faculties", "Eye", "Eyes", "Injury"],
    "Intestinal Ulcers mostly due to alcohol & drugs": ["Stomach", "Upper Stomach", "Lower Stomach", "Bowels", "Intestines", "Abdomen", "Lower Abdomen", "Stomach pain", "Liver"],
    "Intestinal disorders": ["Intestines", "Bowels", "Lower Abdomen", "Stomach pain", "Abdomen"],
    "Irregular heart beats": ["Heart", "Chest", "Blood", "Upper Back", "Nerves problems"],
    "Irregular menses": ["Female Organs", "Ovaries", "Genitals", "Sex Organs", "Blood", "Groins"],
    "Irritation & itching": ["Flesh", "Blood", "Skin"],
    "Itches": ["Flesh", "Blood", "Skin"],
    "Jaundice": ["Liver", "Blood", "Stomach", "Upper Stomach", "Skin", "Eyes"],
    "Kidney stone": ["Kidney", "Urinary Tracts", "Bladder", "Water in the body","Distributary Systems of Body Fluids"],
    "Leg injury": ["Shanks", "Calves", "Knees", "Feet", "Bones", "Flesh", "Injury", "Leg diseases", "Muscle"],
    "Leprosy": ["Flesh", "Blood", "Leprosy", "Skin", "Nerves problems", "Long lasting diseases", "Unknown diseases"],
    "Leucorrhoea": ["Female Organs", "Ovaries", "Genitals", "Sex Organs", "Distributary Systems of Body Fluids"],
    "Liver complaint & problems": ["Liver", "Blood", "Abdomen", "Upper Stomach"],
    "Locomotor ataxia": ["Spine", "Bones", "Joints", "Leg diseases", "Shanks", "Calves"],
    "Loose bowel": ["Stomach", "Hips", "Upper Stomach", "Lower Stomach", "Bowels", "Intestines", "Abdomen", "Lower Abdomen", "Stomach pain"],
    "Low blood pressure": ["Heart", "Chest", "Blood", "Upper Back", "Energy"],
    "Malaria": ["Blood", "Fever", "Liver", "Spleens", "Enlargement of spleen"],
    "Milk leg": ["Shanks", "Calves", "Feet", "Distributary Systems of Body Fluids", "Leg diseases", "Lymphatic System"],
    "Neck problems": ["Neck", "Throat", "Spine", "Shoulders",],
    "Nephritis": ["Kidney", "Urinary Tracts", "Bladder", "Blood", "Water in the body"],
    "Nervous problems": ["Brain", "Mind", "Mental Faculties", "Spine", "Nerves problems", "Psychic Faculty"],
    "Neuralgia, Coma": ["Brain", "Mind", "Mental Faculties", "Head", "Nerves problems", "Memory", "Psychic Faculty", "Speech"],
    "Over heated blood": ["Blood", "Skin", "Fever"],
    "Pain & disorder in the bowels": ["Stomach", "Upper Stomach", "Lower Stomach", "Bowels", "Intestines", "Abdomen", "Lower Abdomen", "Stomach pain"],
    "Pain in the back": ["Upper Back", "Spine", "Waist", "Bones", "Muscle", "Loins"],
    "Pain in the breasts": ["Breast", "Female Organs", "Chest"],
    "Pain in the throat": ["Throat", "Neck", "Respiratory Canal", "Mouth"],
    "Pains in arms and shoulder": ["Arms", "Shoulders", "Collar", "Bones",  "Muscle"],
    "Pains in knee & legs": ["Knees", "Shanks", "Calves", "Thighs", "Bones", "Joints", "Leg diseases", "Muscle"],
    "Pains in the back & head": ["Head", "Brain", "Upper Back", "Spine", "Waist", "Bones", "Muscle"],
    "Pains in the shoulders": ["Shoulders", "Arms", "Collar", "Bones", "Muscle"],
    "Palpitation": ["Heart", "Chest", "Blood", "Upper Back"],
    "Palpitation of heart": ["Heart", "Chest", "Blood", "Upper Back", "Nerves problems"],
    "Paralysis of limbs": ["Spine", "Brain", "Mind", "Mental Faculties", "Nerves problems", "Arms", "Hands", "Leg diseases", "Shanks", "Speech"],
    "Paralytic stroke": ["Head", "Brain", "Mind", "Mental Faculties", "Blood", "Nerves problems", "Memory", "Speech"],
    "Perspiring feet": ["Feet", "Toes", "Skin"],
    "Phlegm": ["Lungs", "Chest", "Breathing", "Breathings", "Throat", "Nose", "Respiratory Canal"],
    "Piles": ["Blood", "Anus", "Bowels", "Excretory Organs", "Skin","Hips"],
    "Piles, Fistula": ["Blood", "Anus", "Bowels", "Excretory Organs", "Skin","Hips"],
    "Fistula": ["Blood", "Anus", "Bowels", "Excretory Organs", "Skin","Hips"],
    "Pimples": ["Flesh", "Blood", "Skin", "Face"],
    "Plague": ["Blood", "Lymphatic System", "Pestilence", "Fever"],
    "Pneumonia": ["Lungs", "Chest", "Breathing", "Breathings", "Throat", "Nose", "Fever", "Lung trouble"],
    "Polyps of nose": ["Nose", "Face", "Respiratory Canal"],
    "Polypus": ["Flesh", "Blood", "Skin"],
    "Poor digestion": ["Stomach", "Upper Stomach", "Lower Stomach", "Bowels", "Intestines", "Abdomen", "Lower Abdomen", "Stomach pain", "Liver"],
    "Problems in kidney & bladder": ["Kidney", "Bladder", "Urinary Tracts", "Water in the body"],
    "Prostate gland enlargement": ["Genitals", "Sex Organs", "Testicles", "Urinary Tracts", "Bladder", "Groins", "Impotency", "Sex urge"],
    "Pulmonary apoplexy": ["Head", "Brain", "Mind", "Mental Faculties", "Lungs", "Chest", "Breathing", "Breathings", "Lung trouble", "Blood"],
    "Pulmonary diseases": ["Lungs", "Chest", "Breathing", "Breathings", "Lung trouble", "Long lasting diseases", "Unknown diseases"],
    "Pulmonary troubles": ["Lungs", "Chest", "Breathing", "Breathings", "Lung trouble"],
    "Pus formation": ["Flesh", "Blood", "Skin"],
    "Reddish eyes": ["Eye", "Eyes", "Face", "Blood"],
    "Respiratory diseases": ["Lungs", "Chest", "Breathing", "Breathings", "Respiratory Canal", "Lung trouble"],
    "Rheumatic heart diseases": ["Heart", "Chest", "Blood", "Joints",],
    "Rheumatic pains": ["Joints", "Bones", "Feet", "Knees", "Hips Joints", "Muscle"],
    "Rheumatism": ["Joints", "Bones", "Thighs", "Knees", "Muscle","Hips"],
    "Severe headache on any one side": ["Head", "Brain", "Mind", "Mental Faculties", "Nerves problems"],
    "Sharp fever": ["Blood", "Fever", "Skin"],
    "Skin diseases": ["Flesh", "Blood", "Skin", "Long lasting diseases", "Unknown diseases"],
    "Skin problems": ["Flesh", "Blood", "Skin"],
    "Small pox": ["Blood", "Skin", "Fever", "Pestilence"],
    "Smallpox": ["Blood", "Skin", "Fever", "Pestilence"],
    "Sore throat": ["Throat", "Neck", "Respiratory Canal", "Mouth", "Pestilence"],
    "Spasms": ["Blood", "Muscle", "Nerves problems"],
    "Spinal Meningitis": ["Blood", "Nerves problems", "Spine", "Brain"],
    "Spotted fever": ["Blood", "Fever", "Skin"],
    "Stomach disorder": ["Stomach", "Upper Stomach", "Lower Stomach", "Stomach pain", "Liver", "Solar Plexes"],
    "Stomach pain": ["Stomach", "Upper Stomach", "Lower Stomach", "Bowels", "Intestines", "Abdomen", "Lower Abdomen", "Stomach pain"],
    "Stomach upset": ["Stomach", "Upper Stomach", "Lower Stomach", "Bowels", "Intestines", "Abdomen", "Lower Abdomen", "Stomach pain"],
    "Suppression of menses, poor bleeding & severe pain": ["Female Organs", "Ovaries", "Genitals", "Sex Organs", "Blood", "Groins"],
    "Swelling above the knees": ["Knees", "Thighs", "Distributary Systems of Body Fluids", "Leg diseases", "Water in the body", "Lymphatic System"],
    "Swelling and pain in the ear": ["Ears", "Distributary Systems of Body Fluids", "Lymphatic System", "Blood", "Water in the body"],
    "Swelling in body": ["Distributary Systems of Body Fluids", "Lymphatic System", "Blood", "Water in the body", "Kidney","Heart", "Liver"],
    "Swelling in the neck": ["Neck", "Throat", "Distributary Systems of Body Fluids", "Lymphatic System", "Blood", "Water in the body"],
    "Swelling of ankle": ["Ankle", "Feet", "Calves", "Distributary Systems of Body Fluids", "Lymphatic System", "Blood", "Leg diseases", "Water in the body","Kidney"],
    "Swollen ankles": ["Ankle", "Feet", "Calves", "Shanks", "Bones", "Joints", "Leg diseases"],
    "Syphilis affecting tube and vision": ["Eye", "Eyes", "Female Organs", "Ovaries", "Genitals", "Sex Organs", "Blood", "Genital", "Skin", "Long lasting diseases", "Impotency"],
    "Temporary mental instability due to blood clotting": ["Head", "Brain", "Mind", "Mental Faculties", "Blood", "Memory"],
    "Throat infections": ["Throat", "Neck", "Mouth", "Pestilence", "Respiratory Canal", "Ears", "Nose"],
    "Tuberculosis": ["Lungs", "Chest", "Breathing", "Breathings", "Throat", "Nose", "Lung trouble", "Long lasting diseases", "Bone Marrow", "Unknown diseases"],
    "Tumours in the bowels": ["Stomach", "Upper Stomach", "Lower Stomach", "Bowels", "Intestines", "Abdomen", "Lower Abdomen", "Stomach pain", "Flesh"],
    "Tumours in the knees": ["Knees", "Bones", "Flesh", "Joints", "Leg diseases"],
    "Typhoid": ["Blood", "Fever", "Bowels", "Intestines", "Pestilence"],
    "Ulceratives in the respiratory system": ["Lungs", "Chest", "Breathing", "Breathings", "Throat", "Nose", "Stomach", "Upper Stomach", "Lower Stomach", "Bowels", "Stomach pain", "Respiratory Canal"],
    "Ulcers": ["Stomach", "Upper Stomach", "Lower Stomach", "Bowels", "Intestines", "Abdomen", "Lower Abdomen", "Stomach pain", "Skin"],
    "Urinary infection": ["Kidney", "Urinary Tracts", "Bladder", "Pestilence", "Water in the body", "Blood"],
    "Urinary trouble": ["Urinary Tracts", "Bladder", "Kidney", "Water in the body"],
    "Venereal distemper": ["Female Organs", "Ovaries", "Genitals", "Sex Organs", "Genital", "Skin", "Blood", "Impotency", "Sex urge"],
    "Violence": ["Head", "Blood", "Injury", "Bones", "Flesh"],
    "Vitamin 'B' deficiency": ["Blood", "Nerves problems", "Energy", "Skin"],
    "Weakness": ["Blood", "Mind", "Energy", "Muscle", "Body Growth", "Fat in the body"],
    "Weakness of arms and shoulder": ["Arms", "Shoulders", "Collar", "Bones", "Joints", "Energy", "Muscle"],
    "Worm infestation": ["Bowels", "Intestines", "Abdomen", "Blood"],
    "Worm infestations": ["Bowels", "Intestines", "Abdomen", "Blood"],
    "Wounds": ["Flesh", "Blood", "Injury", "Skin"],
    "Wounds & Fracture of arms": ["Arms", "Shoulders", "Collar", "Bones", "Flesh", "Blood", "Injury", "Skin"],
    "Wounds from insects": ["Flesh", "Blood", "Injury", "Skin"],
}


def _split_csv(raw: str) -> list[str]:
    return [part.strip() for part in str(raw or "").split(",") if part.strip()]


RASHI_TO_ORGANS = {
    rashi: _split_csv(organs)
    for rashi, organs in RASHI_ORGANS.items()
}

PLANET_TERM_TO_RASHI_ORGANS = dict(NORMALIZED_PLANET_TERM_TO_RASHI_ORGANS)

NAKSHATRA_DISEASE_TO_RASHI_ORGANS = dict(NAKSHATRA_DISEASE_TO_SUPERSET_ORGANS)
 
