TERM_TO_SYSTEMS = { 
    # RASHI ORGANS 
    "Head":           ["neurological", "sensory"], 
    "Brain":          ["neurological", "mental","cardiovascular"], 
    "Mind":           ["mental", "neurological"], 
    "Face":           ["dermatological", "sensory"], 
    "Eye":            ["sensory"], 
    "Eyes":           ["sensory"], 
    "Nose":           ["respiratory", "sensory","dermatological"], 
    "Tongue":         ["digestive", "sensory"], 
    "Ears":           ["sensory","dermatological"], 
    "Fingers":        ["muscular_upper","dermatological"],
    "Navels":         ["digestive","reproductive"],
    "Teeth":          ["digestive", "muscular_upper"],
    "Bones":          ["skeletal"],
    "Flesh":          ["muscular_upper", "muscular_lower","dermatological"],
    "Mouth":          ["digestive", "sensory","dermatological"],
    "Throat":         ["respiratory", "sensory","dermatological"],
    "Neck":           ["muscular_upper", "sensory","dermatological"],
    "Breathings":     ["respiratory"],
    "Breathing":      ["respiratory"],
    "Hands":          ["muscular_upper","dermatological"],
    "Body Growth":    ["systemic", "hormonal"],
    "Shoulders":      ["muscular_upper"],
    "Upper Chest":    ["respiratory", "cardiovascular"],
    "Lungs":          ["respiratory"],
    "Arms":           ["muscular_upper","dermatological"],
    "Breast":         ["reproductive", "lymphatic"],
    "Stomach":        ["digestive"],
    "Heart":          ["cardiovascular","blood","respiratory"],
    "Chest":          ["respiratory", "cardiovascular"],
    "Blood":          ["blood", "cardiovascular","digestive","renal","cancer","dermatological"],
    "Upper Back":     ["muscular_upper", "neurological","dermatological"],
    "Abdomen":        ["digestive"],
    "Upper Stomach":  ["digestive"],
    "Spine":          ["skeletal", "neurological"],
    "Solar Plexes":   ["digestive", "neurological","blood"],
    "Bowels":         ["digestive", "excretory"],
    "Lower Abdomen":  ["digestive", "reproductive", "urogenital"],
    "Naval":          ["digestive","reproductive"],
    "Mental Faculties":["mental", "neurological"],
    "Lower Stomach":  ["digestive"],
    "Intestines":     ["digestive","excretory"],
    "Waist":          ["muscular_lower","dermatological"],
    "Kidney":         ["renal", "urogenital", "hormonal", "detox"],
    "Ovaries":        ["reproductive", "hormonal", "endocrine"],
    "Groins":         ["reproductive", "urogenital","dermatological"],
    "Semen":          ["reproductive", "urogenital"],
    "Female Organs":  ["reproductive", "hormonal","dermatological"],
    "Loins":          ["reproductive", "urogenital","dermatological"],
    "Bladder":        ["urogenital", "renal"],
    "Sex Organs":     ["reproductive", "urogenital","dermatological"],
    "Urinary Tracts": ["urogenital", "renal","reproductive"],
    "Genitals":       ["reproductive", "urogenital","dermatological"],
    "Anus":           ["excretory", "digestive", "locomotor"],
    "Excretory Organs":["excretory", "locomotor"],
    "Hips Joints":    ["locomotor"],
    "Thighs":         ["muscular_lower","locomotor"],
    "Liver":          ["hepatic", "digestive", "metabolic", "hormonal", "detox"],
    "Knees":          ["locomotor"],
    "Spleens":        ["lymphatic", "blood","cardiovascular"],
    "Joints":         ["locomotor","neurological"],
    "Distributary Systems of Body Fluids": ["lymphatic", "renal", "cardiovascular","harmonal","blood","reproductive"],
    "Shanks":         ["muscular_lower","locomotor"],
    "Calves":         ["muscular_lower", "cardiovascular"],
    "Feet":           ["locomotor","dermatological"],
    "Psychic Faculty":["mental", "neurological"],
    "Lymphatic System":["lymphatic", "blood"],
    "Toes":           ["muscular_lower","dermatological"], 
 
    # PLANET ORGAN SYSTEM 
    "Chest":                    ["respiratory", "cardiovascular"], 
    "Water in the body":        ["renal", "lymphatic", "cardiovascular"], 
    "Memory":                   ["mental", "neurological"], 
    "Emotions and Desires":     ["mental"], 
    "Muscle":                   ["muscular_upper", "muscular_lower","cardiovascular"], 
    "Testicles":                ["reproductive", "hormonal"], 
    "Injury":                   ["muscular_upper", "muscular_lower", "systemic","locomotor"], 
    "Bone Marrow":              ["skeletal", "lymphatic"], 
    "Speech":                   ["neurological", "sensory"], 
    "Skin":                     ["dermatological"], 
    "Respiratory Canal":        ["respiratory"], 
    "Hips":                     ["skeletal"], 
    "Genital":                  ["reproductive", "urogenital"], 
    "Sex urge":                 ["reproductive", "hormonal"], 
    "Long lasting diseases":    ["systemic"], 
    "Pestilence":               ["systemic", "lymphatic","respiratory"], 
    "Impotency":                ["reproductive", "hormonal"], 
    "Nerves problems":          ["neurological"], 
    "Gas troubles":             ["digestive","cardiovascular"], 
    "Accute pain":              ["systemic"], 
    "Acute pain":               ["systemic", "infectious"], 
    "Lung trouble":             ["respiratory"], 
    "Difficulty in breathing":  ["respiratory"], 
    "Leprosy":                  ["dermatological", "systemic","cardiovascular"], 
    "Enlargement of spleen":    ["lymphatic", "blood"], 
    "Fever":                    ["systemic", "blood","respiratory"], 
    "Stomach pain":             ["digestive"], 
    "Body pain":                ["systemic", "muscular_upper", "muscular_lower"], 
    "Unknown diseases":         ["systemic"], 
 
    # NAKSHATRA DISEASES 
    "Injury in the head":                    ["neurological", "muscular_upper"],
    "Congestion in the brain":               ["neurological", "cardiovascular"],
    "Cerebral anaemia":                      ["neurological", "blood"],
    "Fainting":                              ["neurological", "cardiovascular"],
    "Epilepsy":                              ["neurological"],
    "Violence":                              ["systemic"],
    "Spasms":                                ["neurological", "muscular_upper", "muscular_lower"],
    "Severe headache on any one side":       ["neurological"],
    "Neuralgia, Coma":                       ["neurological"],
    "Cerebral haemorrhages":                 ["neurological", "cardiovascular", "blood"],
    "Paralytic stroke":                      ["neurological", "cardiovascular"],
    "Smallpox":                              ["dermatological", "systemic", "infectious"],
    "Injury in the head mostly in the forehead, just around the eyes": ["neurological", "sensory", "muscular_upper"],
    "Cold":                                  ["respiratory", "systemic", "infectious"],
    "Venereal distemper":                    ["reproductive", "dermatological", "infectious"],
    "Syphilis affecting tube and vision":    ["reproductive", "sensory", "systemic", "infectious"],
    "Weakness":                              ["systemic"],
    "Sharp fever":                           ["systemic", "blood","respiratory", "infectious"],
    "Malaria":                               ["blood", "systemic", "infectious"],
    "Filaria":                               ["lymphatic", "systemic", "infectious"],
    "Plague":                                ["systemic", "lymphatic", "infectious"],
    "Wounds":                                ["muscular_upper", "muscular_lower", "dermatological"],
    "Brain fever":                           ["neurological", "systemic"],
    "Accident including fire accidents":     ["systemic", "muscular_upper", "muscular_lower"],
    "Pimples":                               ["dermatological", "infectious"],
    "Cuts":                                  ["dermatological", "muscular_upper", "muscular_lower"],
    "Reddish eyes":                          ["sensory", "infectious"],
    "Eye sore":                              ["sensory", "infectious"],
    "Throat infections":                     ["respiratory", "sensory", "infectious"],
    "Tumours in the knees":                  ["locomotor","muscular_lower"],
    "Neck problems":                         ["muscular_upper", "sensory"],
    "Polyps of nose":                        ["respiratory", "sensory"],
    "Sore throat":                           ["respiratory", "infectious"],
    "Cold & Cough":                          ["respiratory", "infectious"],
    "Irregular menses":                      ["reproductive", "hormonal"],
    "Pain in the breasts":                   ["reproductive", "lymphatic"],
    "Injury in the face":                    ["muscular_upper", "sensory"],
    "Pain in the throat":                    ["respiratory", "sensory", "infectious"],
    "Diphtheria":                            ["respiratory", "systemic", "infectious"],
    "Polypus":                               ["respiratory", "sensory"],
    "Corrupted blood":                       ["blood", "systemic","digestive"],
    "Itches":                                ["dermatological"],
    "Wounds & Fracture of arms/legs":        ["muscular_upper", "muscular_lower"],
    "Collar bone fracture":                  ["muscular_upper"],
    "Pains in the shoulders":               ["muscular_upper"], 
    "Asthma":                               ["respiratory", "infectious"], 
    "Dry coughs":                           ["respiratory"], 
    "Ear infections":                       ["sensory", "infectious"], 
    "Eosinophilia":                         ["blood", "respiratory", "lymphatic", "infectious"], 
    "Swelling and pain in the ear":         ["sensory"], 
    "Goitre due to Iodine deficiency":      ["hormonal", "endocrine"], 
    "Pulmonary apoplexy":                   ["respiratory", "cardiovascular"], 
    "Dropsy":                               ["renal", "cardiovascular", "lymphatic"], 
    "Beri beri":                            ["systemic", "neurological"], 
    "Stomach upset":                        ["digestive", "infectious"], 
    "Tuberculosis":                         ["respiratory", "systemic", "infectious"],
    "Pneumonia":                            ["respiratory", "infectious"], 
    "Liver complaint & problems":           ["hepatic", "digestive", "metabolic"], 
    "Ulceratives in the respiratory system":["respiratory"], 
    "Gastric ulcer":                        ["digestive"], 
    "Gallstones":                           ["hepatic", "digestive"], 
    "Cancer":                               ["systemic"], 
    "Cough & hiccups":                      ["respiratory", "digestive"], 
    "Eczema":                               ["dermatological", "infectious"], 
    "Pains in knee & legs":                ["locomotor"],
    "Nervous problems":                    ["neurological"],
    "Indigestion":                         ["digestive"],
    "Heart affected by sudden shock":      ["cardiovascular", "mental"],
    "Pain in the back":                    ["muscular_upper", "muscular_lower", "neurological","cardiovascular"],
    "Kidney stone":                        ["renal", "urogenital"],
    "Spinal Meningitis":                   ["neurological", "skeletal", "infectious"],
    "Heart affected due to disappointment of love affairs": ["cardiovascular", "mental"],
    "Heart affects due to loss of children":               ["cardiovascular", "mental"],
    "Swelling of ankle":                   ["muscular_lower","renal"],
    "Blood pressure":                      ["cardiovascular", "blood"],
    "Heart Valves affected":               ["cardiovascular","blood"],
    "Curvature of spine":                  ["skeletal", "neurological"],
    "Pains in the back & head":            ["muscular_upper", "neurological","cardiovascular","digestive", "infectious"],
    "Spotted fever":                       ["blood", "systemic", "infectious"],
    "Hyperaemia":                          ["cardiovascular", "blood"],
    "Temporary mental instability due to blood clotting": ["neurological", "blood", "mental"],
    "Palpitation":                         ["cardiovascular"],
    "Tumours in the bowels":               ["digestive"],
    "Stomach disorder":                    ["digestive", "infectious"],
    "Swelling in the neck":               ["muscular_upper", "lymphatic"],
    "Gas formation":                       ["digestive", "infectious"],
    "Loose bowel":                         ["digestive", "excretory", "infectious"],
    "Pain & disorder in the bowels":      ["digestive", "excretory"],
    "Weakness of arms and shoulder":      ["muscular_upper"], 
    "Breathing problems":                 ["respiratory", "infectious"], 
    "Worm infestations":                  ["digestive", "systemic", "infectious"],
    "Typhoid":                            ["digestive", "systemic", "infectious"],
    "Bacillary dysentery":               ["digestive", "excretory", "infectious"], 
    "Hysteria":                          ["mental", "neurological"], 
    "Ulcers":                            ["digestive", "dermatological"], 
    "Acute pains in the body":           ["systemic", "infectious"], 
    "Choleric humours":                  ["digestive", "mental", "infectious"], 
    "Irritation & itching":             ["dermatological"], 
    "Wounds from insects":              ["dermatological", "systemic"], 
    "Problems in kidney & bladder":     ["renal", "urogenital"], 
    "Excess of urine and kidney problem":["renal", "urogenital"], 
    "Pus formation":                    ["dermatological", "systemic", "infectious"],
    "Skin problems":                    ["dermatological", "infectious"], 
    "Urinary infection":               ["urogenital", "renal"], 
    "Deficiency of adrenal secretion": ["hormonal", "renal", "endocrine"], 
    "Diabetes, Insulin deficiency": ["metabolic", "hormonal", "endocrine", "renal"], 
    "Congestion of brain":             ["neurological", "cardiovascular"], 
    "Diseases of womb":               ["reproductive", "hormonal"], 
    "Fibroid tumour":                 ["reproductive"], 
    "Prostate gland enlargement":     ["reproductive", "urogenital"], 
    "Urinary trouble":               ["urogenital", "renal", "infectious"], 
    "Frequent micturition":          ["urogenital","reproductive"], 
    "Abnormal bleeding during menses":["reproductive", "hormonal", "blood"], 
    "Suppression of menses, poor bleeding & severe pain": ["reproductive", "hormonal"], 
    "Piles":                         ["excretory", "digestive", "blood", "locomotor"],
    "Piles, Fistula":               ["excretory", "digestive", "blood", "locomotor"],
    "Phlegm":                       ["respiratory", "infectious"],
    "Fracture of hip bone":         ["skeletal"],
    "Leucorrhoea":                  ["reproductive", "urogenital"],
    "Affliction of bowels":        ["digestive", "locomotor"],
    "Pains in arms and shoulder":  ["muscular_upper"],
    "Locomotor ataxia":            ["locomotor"],
    "Rheumatism":                  ["locomotor", "systemic","cardiovascular"],
    "Hip diseases":                ["locomotor","digestive"],
    "Pulmonary troubles":          ["respiratory", "infectious"],
    "Diabetes":                    ["metabolic", "hormonal", "renal","cardiovascular", "blood"],
    "Respiratory diseases":        ["respiratory"],
    "Swelling above the knees":   ["cardiovascular"],
    "Paralysis of limbs":         ["neurological", "locomotor"],
    "Pulmonary diseases":         ["respiratory"],
    "Affected eyes":              ["sensory", "infectious"],
    "Skin diseases":              ["dermatological", "infectious"],
    "Digestive disorders":        ["digestive"],
    "Gas in stomach":            ["digestive"],
    "Palpitation of heart":      ["cardiovascular"],
    "Cardiac thrombosis":        ["cardiovascular", "blood"],
    "Leg injury":                ["muscular_lower", "locomotor"],
    "Hiccups":                   ["respiratory"],
    "Amputation":                ["muscular_upper", "muscular_lower"],
    "Fracture of legs":          ["skeletal"],
    "Blood poisoning":           ["blood", "systemic"],
    "Heart failure":             ["cardiovascular"],
    "High Blood pressure":       ["cardiovascular", "blood"],
    "Over heated blood":         ["blood", "cardiovascular"],
    "Rheumatic heart diseases":  ["cardiovascular", "blood"],
    "Fracture":                  ["skeletal"],
    "Worm infestation":         ["digestive", "systemic"],
    "Apoplexy":                 ["neurological", "cardiovascular"],
    "Irregular heart beats":    ["cardiovascular"],
    "Milk leg":                 ["cardiovascular", "muscular_lower"],
    "Swollen ankles":           ["cardiovascular", "muscular_lower"],
    "Dilated heart":            ["cardiovascular"],
    "Low blood pressure":       ["cardiovascular", "blood"],
    "Swelling in body":        ["lymphatic", "cardiovascular", "renal"],
    "Enlarged Liver":          ["hepatic", "digestive", "metabolic"],
    "Abdominal tumour":        ["digestive", "reproductive"],
    "Intestinal disorders":    ["digestive", "infectious"],
    "Jaundice":               ["hepatic", "blood", "infectious"],
    "Rheumatic pains":        ["locomotor", "systemic"],
    "Constipation":           ["digestive", "excretory"],
    "Hernia":                 ["digestive", "muscular_lower"],
    "Cold foot":              ["muscular_lower", "cardiovascular"],
    "Fracture in foot":       ["skeletal"], 
    "Abdominal disorders":    ["digestive"], 
    "Intestinal Ulcers mostly due to alcohol & drugs": ["digestive", "hepatic"], 
    "Nephritis":              ["renal", "urogenital"], 
    "Poor digestion":         ["digestive"], 
    "Poor digestion/indigestion": ["digestive"],
}

SYSTEM_DISPLAY_NAMES = {
    "renal":          "Kidney / Renal",
    "urogenital":     "Urinary / Urogenital",
    "reproductive":   "Reproductive / Genital",
    "hormonal":       "Hormonal / Endocrine",
    "endocrine":      "Hormonal / Endocrine",
    "metabolic":      "Metabolic / Diabetes",
    "digestive":      "Digestive / Abdominal",
    "hepatic":        "Liver / Hepatic",
    "detox":          "Detox / Filtration",
    "respiratory":    "Respiratory / Lungs",
    "cardiovascular": "Cardiovascular / Heart",
    "blood":          "Blood / Circulatory",
    "neurological":   "Neurological / Brain",
    "skeletal":       "Bones / Skeletal",
    "locomotor":      "Hip Region / Joints / Locomotor",
    "muscular_upper": "Muscles Upper Body",
    "muscular_lower": "Muscles Lower Body",
    "dermatological": "Skin / Dermatological",
    "lymphatic":      "Lymphatic / Immunity",
    "sensory":        "Sensory / Eyes / Ears",
    "mental":         "Mental / Emotional",
    "excretory":      "Excretory / Digestive",
    "systemic":       "Whole Body/ Systemic",
    "infectious":     "Infections / Contagious",
}

# Systems that should be merged in final display
MERGE_GROUPS = {
    "renal_urogenital": { 
        "systems": ["renal", "urogenital"], 
        "label":   "Kidney / Urinary System" 
    }, 
    "reproductive": { 
        "systems": ["reproductive"], 
        "label":   "Reproductive System" 
    }, 
    "hormonal_metabolic": { 
        "systems": ["hormonal", "endocrine", "metabolic"], 
        "label":   "Hormonal & Metabolic" 
    }, 
    "digestive_hepatic": { 
        "systems": ["digestive", "hepatic"], 
        "label":   "Digestive / Liver" 
    }, 
    "cardiovascular_blood": { 
        "systems": ["cardiovascular", "blood"], 
        "label":   "Heart / Blood" 
    }, 
    "neurological_mental": { 
        "systems": ["neurological", "mental"], 
        "label":   "Brain / Nervous System" 
    }, 
    "skeletal": { 
        "systems": ["skeletal"], 
        "label":   "Bones / Skeletal" 
    }, 
    "locomotor": { 
        "systems": ["locomotor"], 
        "label":   "Hip Disease/ Joints / Locomotor" 
    }, 
    "muscular_upper": { 
        "systems": ["muscular_upper"], 
        "label":   "Muscles Upper Body" 
    }, 
    "muscular_lower": { 
        "systems": ["muscular_lower"], 
        "label":   "Muscles Lower Body" 
    }, 
    "respiratory": { 
        "systems": ["respiratory"], 
        "label":   "Respiratory / Lungs" 
    }, 
    "dermatological_lymphatic": { 
        "systems": ["dermatological", "lymphatic"], 
        "label":   "Skin / Immunity/ Sensory" 
    }, 
    "sensory": { 
        "systems": ["sensory"], 
        "label":   "Sensory / Eyes / Ears" 
    }, 
    "excretory": { 
        "systems": ["excretory"], 
        "label":   "Excretory System" 
    }, 
    "systemic": { 
        "systems": ["systemic", "detox"], 
        "label":   "Systemic / Whole Body" 
    }, 
    "infectious": { 
        "systems": ["infectious"], 
        "label":   "Infections / Contagious" 
    }, 
}
