import logging
import math
from typing import Any, Dict, List, Optional, Union

_LOG = logging.getLogger(__name__)

# Keys to strip before serialization
_OMIT = {"_id", "_rev", "raw_response"}
ALGORITHM_VERSION = "1.0.0"


# ==========================================
# HELPER & SANITIZATION FUNCTIONS
# ==========================================

def _sanitize_for_json(value: Any) -> Any:
    if isinstance(value, float):
        if math.isnan(value) or math.isinf(value):
            return None
        return value

    if isinstance(value, dict):
        return {
            str(key): _sanitize_for_json(item)
            for key, item in value.items()
            if key not in _OMIT
        }

    if isinstance(value, (list, tuple)):
        return [_sanitize_for_json(item) for item in value]

    return value


def _shrink(data: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    """Strips internal or redundant payload metadata from a dictionary."""
    if not data or not isinstance(data, dict):
        return {}
    return {k: v for k, v in data.items() if k not in _OMIT}


def _fit(data: Dict[str, Any]) -> Dict[str, Any]:
    """Prepares and cleans a payload dictionary for database persistence."""
    if not isinstance(data, dict):
        return {}
    return _sanitize_for_json(data)


def algorithm_result_id(input_id: str, algorithm_name: str) -> str:
    """Generates a deterministic document ID for an algorithm result."""
    return f"{input_id}_{algorithm_name}"


def chart_input_id(patient_id: str, timestamp_str: str) -> str:
    """Generates a deterministic document ID for chart inputs."""
    return f"{patient_id}_{timestamp_str}"


# ==========================================
# CHART PERSISTENCE CLASS
# ==========================================

class ChartPersistence:
    """Handles persistence operations for astrology/chart generations, inputs, 
    raw responses, planetary data, and algorithm outputs.
    """

    def __init__(self, repository: Any) -> None:
        self.repository = repository
        _LOG.info(
            "chart_persistence_initialized",
            extra={"repository_type": type(repository).__name__},
        )

    # ------------------------------------------------------------------
    # CORE SAVE GENERATION WORKFLOW
    # ------------------------------------------------------------------

    def save_generation(
        self,
        internal_user_id: str,
        chart_input: Dict[str, Any],
        patient_id: str,
        source: str,
        response: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Persist one chart generation under the authenticated user."""

        if not isinstance(chart_input, dict):
            chart_input = {}

        if not isinstance(response, dict):
            response = {}

        # The input ID must be stable for this generation.
        input_id = response.get("input_id")

        if not input_id:
            input_id = chart_input.get("input_id")

        if not input_id:
            # Patient IDs are already generated by the chart pipeline.
            # Include a timestamp so repeated generations do not overwrite
            # each other.
            from datetime import datetime, timezone

            timestamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S%f")
            input_id = chart_input_id(patient_id, timestamp)

        # Always persist the authenticated owner.
        input_payload = _fit({
            **chart_input,
            "input_id": input_id,
            "patient_id": patient_id,
            "source": source,
            "record_type": "input",
            "owner_internal_user_id": internal_user_id,
            "profile": {
                "name": chart_input.get("name", ""),
                "dob": chart_input.get("dob", ""),
                "birth_time": chart_input.get("birth_time", ""),
                "birth_place": chart_input.get("birth_place", ""),
                "gender": chart_input.get("gender", ""),
                "lat": chart_input.get("lat"),
                "lng": chart_input.get("lng"),
            },
        })


        self.repository.save(
            internal_user_id,
            "inputs",
            input_id,
            input_payload,
        )

        # Keep the chart-specific input collection available too.
        self.repository.save(
            internal_user_id,
            "chart_inputs",
            input_id,
            input_payload,
        )

        # Bind the patient to the authenticated user.
        self.repository.bind_patient(
            internal_user_id,
            patient_id,
            input_id,
        )

        # Persist the provider/prokerala portion if present.
        prokerala_result = (
            response.get("prokerala_result")
            or response.get("prokerala_results")
            or response.get("raw_response")
        )

        if prokerala_result is not None:
            self.repository.save(
                internal_user_id,
                "prokerala_results",
                input_id,
                _fit({
                    "input_id": input_id,
                    "patient_id": patient_id,
                    "payload": prokerala_result,
                    "source": source,
                }),
            )

        # Persist algorithm results.
        algorithm_names = [
            key
            for key in response
            if key not in {
                "input",
                "input_id",
                "raw_response",
                "prokerala_result",
                "prokerala_results",
                "planetary_positions",
            }
        ]

        algorithm_ids = []

        for name in algorithm_names:
            value = response.get(name)

            # Only persist dictionary/list algorithm payloads.
            if not isinstance(value, (dict, list)):
                continue

            doc_id = algorithm_result_id(input_id, name)

            algorithm_document = _fit({
                "record_type": "algorithm",
                "algorithm": name,
                "algorithm_version": ALGORITHM_VERSION,
                "input_id": input_id,
                "prokerala_result_id": input_id,
                "patient_id": patient_id,
                "source": "rules_engine",
                "status": "complete",
                "output": value,
            })

            print("=== PERSISTENCE DEBUG ===", flush=True)
            print(f"internal_user_id = {internal_user_id!r}", flush=True)
            print(f"collection = {'inputs'!r}", flush=True)
            print(f"input_id = {input_id!r}", flush=True)
            print("=========================", flush=True)

            self.repository.save(
                internal_user_id,
                "algorithm_results",
                doc_id,
                algorithm_document,
            )

            algorithm_ids.append(doc_id)

                # Persist the combined result for this generation.
        # This is the report-level record that ties the individual
        # algorithm outputs back to one chart generation.
        combined_document = _fit({
            "record_type": "combined",
            "input_id": input_id,
            "patient_id": patient_id,
            "source": source,
            "status": "complete",
            "algorithm_ids": algorithm_ids,
            "algorithm_count": len(algorithm_ids),
        })

        print("=== COMBINED SAVE DEBUG ===")
        print("internal_user_id:", repr(internal_user_id), type(internal_user_id))
        print("collection:", repr("combined_results"), type("combined_results"))
        print("doc_id/input_id:", repr(input_id), type(input_id))
        print("combined_document:", combined_document)
        print("===========================")

        self.repository.save(
            internal_user_id,
            "combined_results",
            input_id,
            combined_document,
        )

        return {
            "input_id": input_id,
            "patient_id": patient_id,
            "total_requested": len(algorithm_names),
            "total_saved": len(algorithm_ids),
            "algorithm_ids": algorithm_ids,
        }

    # ------------------------------------------------------------------
    # RETRIEVAL AND QUERY METHODS
    # ------------------------------------------------------------------

    def get_chart_input(
        self, internal_user_id: str, input_id: str
    ) -> Optional[Dict[str, Any]]:
        """Retrieves saved chart input data by input_id."""
        _LOG.info(
            "get_chart_input_started",
            extra={"operation": "get_chart_input", "input_id": input_id},
        )
        try:
            result = self.repository.get(internal_user_id, "chart_inputs", input_id)
            if result:
                _LOG.info(
                    "get_chart_input_found",
                    extra={"operation": "get_chart_input", "input_id": input_id},
                )
            else:
                _LOG.warning(
                    "get_chart_input_not_found",
                    extra={"operation": "get_chart_input", "input_id": input_id},
                )
            return result
        except Exception as exc:
            _LOG.exception(
                "get_chart_input_failed",
                extra={
                    "operation": "get_chart_input",
                    "input_id": input_id,
                    "error_type": type(exc).__name__,
                    "error_message": str(exc),
                },
            )
            raise

    def get_algorithm_result(
        self, internal_user_id: str, input_id: str, algorithm_name: str
    ) -> Optional[Dict[str, Any]]:
        """Retrieves a single saved algorithm result by input_id and algorithm name."""
        doc_id = algorithm_result_id(input_id, algorithm_name)
        _LOG.info(
            "get_algorithm_result_started",
            extra={
                "operation": "get_algorithm_result",
                "input_id": input_id,
                "algorithm": algorithm_name,
                "doc_id": doc_id,
            },
        )
        try:
            result = self.repository.get(internal_user_id, "algorithm_results", doc_id)
            if result:
                _LOG.info(
                    "get_algorithm_result_found",
                    extra={"operation": "get_algorithm_result", "doc_id": doc_id},
                )
            else:
                _LOG.warning(
                    "get_algorithm_result_not_found",
                    extra={"operation": "get_algorithm_result", "doc_id": doc_id},
                )
            return result
        except Exception as exc:
            _LOG.exception(
                "get_algorithm_result_failed",
                extra={
                    "operation": "get_algorithm_result",
                    "doc_id": doc_id,
                    "error_type": type(exc).__name__,
                    "error_message": str(exc),
                },
            )
            raise

    def get_raw_response(
        self, internal_user_id: str, input_id: str
    ) -> Optional[Dict[str, Any]]:
        """Retrieves raw API response data by input_id."""
        _LOG.info(
            "get_raw_response_started",
            extra={"operation": "get_raw_response", "input_id": input_id},
        )
        try:
            result = self.repository.get(internal_user_id, "raw_responses", input_id)
            if result:
                _LOG.info(
                    "get_raw_response_found",
                    extra={"operation": "get_raw_response", "input_id": input_id},
                )
            else:
                _LOG.warning(
                    "get_raw_response_not_found",
                    extra={"operation": "get_raw_response", "input_id": input_id},
                )
            return result
        except Exception as exc:
            _LOG.exception(
                "get_raw_response_failed",
                extra={
                    "operation": "get_raw_response",
                    "input_id": input_id,
                    "error_type": type(exc).__name__,
                    "error_message": str(exc),
                },
            )
            raise

    def get_planetary_positions(
        self, internal_user_id: str, input_id: str
    ) -> Optional[Dict[str, Any]]:
        """Retrieves planetary positions by input_id."""
        _LOG.info(
            "get_planetary_positions_started",
            extra={"operation": "get_planetary_positions", "input_id": input_id},
        )
        try:
            result = self.repository.get(
                internal_user_id, "planetary_positions", input_id
            )
            if result:
                _LOG.info(
                    "get_planetary_positions_found",
                    extra={
                        "operation": "get_planetary_positions",
                        "input_id": input_id,
                    },
                )
            else:
                _LOG.warning(
                    "get_planetary_positions_not_found",
                    extra={
                        "operation": "get_planetary_positions",
                        "input_id": input_id,
                    },
                )
            return result
        except Exception as exc:
            _LOG.exception(
                "get_planetary_positions_failed",
                extra={
                    "operation": "get_planetary_positions",
                    "input_id": input_id,
                    "error_type": type(exc).__name__,
                    "error_message": str(exc),
                },
            )
            raise

    def list_patient_chart_inputs(
        self, internal_user_id: str, patient_id: str
    ) -> List[Dict[str, Any]]:
        """Lists all chart inputs associated with a specific patient ID."""
        _LOG.info(
            "list_patient_chart_inputs_started",
            extra={
                "operation": "list_patient_chart_inputs",
                "patient_id": patient_id,
            },
        )
        try:
            results = self.repository.query(
                internal_user_id,
                "chart_inputs",
                field="patient_id",
                value=patient_id,
            )
            _LOG.info(
                "list_patient_chart_inputs_completed",
                extra={
                    "operation": "list_patient_chart_inputs",
                    "patient_id": patient_id,
                    "count": len(results) if results else 0,
                },
            )
            return results or []
        except Exception as exc:
            _LOG.exception(
                "list_patient_chart_inputs_failed",
                extra={
                    "operation": "list_patient_chart_inputs",
                    "patient_id": patient_id,
                    "error_type": type(exc).__name__,
                    "error_message": str(exc),
                },
            )
            raise

    # ------------------------------------------------------------------
    # UPDATE AND DELETE METHODS
    # ------------------------------------------------------------------

    def update_algorithm_result(
        self,
        internal_user_id: str,
        input_id: str,
        algorithm_name: str,
        output_data: Dict[str, Any],
    ) -> bool:
        """Updates an existing algorithm result entry."""
        doc_id = algorithm_result_id(input_id, algorithm_name)
        _LOG.info(
            "update_algorithm_result_started",
            extra={
                "operation": "update_algorithm_result",
                "input_id": input_id,
                "algorithm": algorithm_name,
                "doc_id": doc_id,
            },
        )
        try:
            sanitized_output = _sanitize_for_json(output_data)
            update_payload = _fit(
                {
                    "output": sanitized_output,
                    "status": "updated",
                    "algorithm_version": ALGORITHM_VERSION,
                }
            )
            self.repository.update(
                internal_user_id,
                "algorithm_results",
                doc_id,
                update_payload,
            )
            _LOG.info(
                "update_algorithm_result_completed",
                extra={"operation": "update_algorithm_result", "doc_id": doc_id},
            )
            return True
        except Exception as exc:
            _LOG.exception(
                "update_algorithm_result_failed",
                extra={
                    "operation": "update_algorithm_result",
                    "doc_id": doc_id,
                    "error_type": type(exc).__name__,
                    "error_message": str(exc),
                },
            )
            raise

    def delete_generation(
        self, internal_user_id: str, input_id: str, algorithm_names: List[str]
    ) -> bool:
        """Deletes chart inputs, raw responses, planetary positions, 
        and algorithm outputs for a given input ID.
        """
        _LOG.info(
            "delete_generation_started",
            extra={
                "operation": "delete_generation",
                "input_id": input_id,
                "algorithm_count": len(algorithm_names),
            },
        )
        try:
            # Delete inputs, raw responses, and planetary positions
            self.repository.delete(internal_user_id, "chart_inputs", input_id)
            self.repository.delete(internal_user_id, "raw_responses", input_id)
            self.repository.delete(internal_user_id, "planetary_positions", input_id)

            # Delete algorithm results
            for name in algorithm_names:
                doc_id = algorithm_result_id(input_id, name)
                self.repository.delete(
                    internal_user_id, "algorithm_results", doc_id
                )

            _LOG.info(
                "delete_generation_completed",
                extra={"operation": "delete_generation", "input_id": input_id},
            )
            return True
        except Exception as exc:
            _LOG.exception(
                "delete_generation_failed",
                extra={
                    "operation": "delete_generation",
                    "input_id": input_id,
                    "error_type": type(exc).__name__,
                    "error_message": str(exc),
                },
            )
            raise